// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/ampulla/api/v1"
)

// BackupPolicySpecApplyConfiguration represents a declarative configuration of the BackupPolicySpec type for use
// with apply.
//
// BackupPolicySpec describes how the service next to it is backed up.
//
// Every field is optional: an empty spec takes the controller's defaults, which is what a
// chart renders when its values say no more than that backups are enabled.
type BackupPolicySpecApplyConfiguration struct {
	// Mode selects who takes the backups.
	Mode *apiv1.Mode `json:"mode,omitempty"`
	// Schedule is when each of the jobs runs. Mode Schedule only.
	Schedule *ScheduleSpecApplyConfiguration `json:"schedule,omitempty"`
	// BucketClassName is the object storage the backups are written to. Empty takes the
	// controller's default; without either, the policy fails rather than being backed up
	// somewhere arbitrary.
	BucketClassName *string `json:"bucketClassName,omitempty"`
	// BucketAccessClassName is the class the bucket credentials are minted from. Empty
	// takes the controller's default.
	BucketAccessClassName *string `json:"bucketAccessClassName,omitempty"`
	// Retention is how many backups survive a prune. All zero takes the controller's
	// default retention. Mode Schedule only.
	Retention *RetentionApplyConfiguration `json:"retention,omitempty"`
}

// BackupPolicySpecApplyConfiguration constructs a declarative configuration of the BackupPolicySpec type for use with
// apply.
func BackupPolicySpec() *BackupPolicySpecApplyConfiguration {
	return &BackupPolicySpecApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *BackupPolicySpecApplyConfiguration) WithMode(value apiv1.Mode) *BackupPolicySpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *BackupPolicySpecApplyConfiguration) WithSchedule(value *ScheduleSpecApplyConfiguration) *BackupPolicySpecApplyConfiguration {
	b.Schedule = value
	return b
}

// WithBucketClassName sets the BucketClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BucketClassName field is set to the value of the last call.
func (b *BackupPolicySpecApplyConfiguration) WithBucketClassName(value string) *BackupPolicySpecApplyConfiguration {
	b.BucketClassName = &value
	return b
}

// WithBucketAccessClassName sets the BucketAccessClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BucketAccessClassName field is set to the value of the last call.
func (b *BackupPolicySpecApplyConfiguration) WithBucketAccessClassName(value string) *BackupPolicySpecApplyConfiguration {
	b.BucketAccessClassName = &value
	return b
}

// WithRetention sets the Retention field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retention field is set to the value of the last call.
func (b *BackupPolicySpecApplyConfiguration) WithRetention(value *RetentionApplyConfiguration) *BackupPolicySpecApplyConfiguration {
	b.Retention = value
	return b
}
