// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/ampulla/api/v1"
)

// BackupPolicyStatusApplyConfiguration represents a declarative configuration of the BackupPolicyStatus type for use
// with apply.
//
// BackupPolicyStatus is where the bucket's coordinates are published. In ModeBucketOnly
// they are the whole deliverable: they are how a service's own backup resource is pointed
// at the storage ampulla provisioned.
type BackupPolicyStatusApplyConfiguration struct {
	Phase *apiv1.BackupPolicyPhase `json:"phase,omitempty"`
	// ObservedGeneration is the spec generation the phase was computed from.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Message explains a Pending or Failed phase.
	Message *string `json:"message,omitempty"`
	// Bucket is the bucket as clients address it.
	Bucket *string `json:"bucket,omitempty"`
	// Endpoint is the object storage endpoint the bucket lives behind.
	Endpoint *string `json:"endpoint,omitempty"`
	// CredentialsSecret is the secret in this namespace holding the bucket's key pair,
	// one value per key. A service that backs itself up reads its S3 credentials there.
	CredentialsSecret *string `json:"credentialsSecret,omitempty"`
	// Schedule is the schedule the backups run on, once defaults are resolved.
	Schedule *string `json:"schedule,omitempty"`
}

// BackupPolicyStatusApplyConfiguration constructs a declarative configuration of the BackupPolicyStatus type for use with
// apply.
func BackupPolicyStatus() *BackupPolicyStatusApplyConfiguration {
	return &BackupPolicyStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *BackupPolicyStatusApplyConfiguration) WithPhase(value apiv1.BackupPolicyPhase) *BackupPolicyStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BackupPolicyStatusApplyConfiguration) WithObservedGeneration(value int64) *BackupPolicyStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *BackupPolicyStatusApplyConfiguration) WithMessage(value string) *BackupPolicyStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *BackupPolicyStatusApplyConfiguration) WithBucket(value string) *BackupPolicyStatusApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *BackupPolicyStatusApplyConfiguration) WithEndpoint(value string) *BackupPolicyStatusApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithCredentialsSecret sets the CredentialsSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredentialsSecret field is set to the value of the last call.
func (b *BackupPolicyStatusApplyConfiguration) WithCredentialsSecret(value string) *BackupPolicyStatusApplyConfiguration {
	b.CredentialsSecret = &value
	return b
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *BackupPolicyStatusApplyConfiguration) WithSchedule(value string) *BackupPolicyStatusApplyConfiguration {
	b.Schedule = &value
	return b
}
