// Code generated by controller-gen. DO NOT EDIT.

package v1

// RetentionApplyConfiguration represents a declarative configuration of the Retention type for use
// with apply.
//
// Retention mirrors restic's forget policy, minus the tag and hostname filters: ampulla
// owns one repository per policy, so there is nothing to filter within it.
type RetentionApplyConfiguration struct {
	KeepLast    *int `json:"keepLast,omitempty"`
	KeepHourly  *int `json:"keepHourly,omitempty"`
	KeepDaily   *int `json:"keepDaily,omitempty"`
	KeepWeekly  *int `json:"keepWeekly,omitempty"`
	KeepMonthly *int `json:"keepMonthly,omitempty"`
	KeepYearly  *int `json:"keepYearly,omitempty"`
}

// RetentionApplyConfiguration constructs a declarative configuration of the Retention type for use with
// apply.
func Retention() *RetentionApplyConfiguration {
	return &RetentionApplyConfiguration{}
}

// WithKeepLast sets the KeepLast field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepLast field is set to the value of the last call.
func (b *RetentionApplyConfiguration) WithKeepLast(value int) *RetentionApplyConfiguration {
	b.KeepLast = &value
	return b
}

// WithKeepHourly sets the KeepHourly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepHourly field is set to the value of the last call.
func (b *RetentionApplyConfiguration) WithKeepHourly(value int) *RetentionApplyConfiguration {
	b.KeepHourly = &value
	return b
}

// WithKeepDaily sets the KeepDaily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepDaily field is set to the value of the last call.
func (b *RetentionApplyConfiguration) WithKeepDaily(value int) *RetentionApplyConfiguration {
	b.KeepDaily = &value
	return b
}

// WithKeepWeekly sets the KeepWeekly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepWeekly field is set to the value of the last call.
func (b *RetentionApplyConfiguration) WithKeepWeekly(value int) *RetentionApplyConfiguration {
	b.KeepWeekly = &value
	return b
}

// WithKeepMonthly sets the KeepMonthly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepMonthly field is set to the value of the last call.
func (b *RetentionApplyConfiguration) WithKeepMonthly(value int) *RetentionApplyConfiguration {
	b.KeepMonthly = &value
	return b
}

// WithKeepYearly sets the KeepYearly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeepYearly field is set to the value of the last call.
func (b *RetentionApplyConfiguration) WithKeepYearly(value int) *RetentionApplyConfiguration {
	b.KeepYearly = &value
	return b
}
