// Code generated by controller-gen. DO NOT EDIT.

package v1

// ScheduleSpecApplyConfiguration represents a declarative configuration of the ScheduleSpec type for use
// with apply.
//
// ScheduleSpec is when the k8up jobs run. Every field is a cron expression or one of
// k8up's shortcuts such as `@daily-random`.
//
// An empty field falls back to the controller's default for that job, and removing one
// from a policy that had it set restores that fallback - and drops the job entirely if the
// controller has no default for it either.
type ScheduleSpecApplyConfiguration struct {
	// Backup is when the backup itself runs. Falls back to the controller's default.
	Backup *string `json:"backup,omitempty"`
	// Prune is when old snapshots are forgotten and pruned. Falls back to the controller's
	// default; with no default configured there, no prune job is scheduled.
	Prune *string `json:"prune,omitempty"`
	// Check is when the backup repository is verified. Falls back to the controller's
	// default; with no default configured there, no check job is scheduled.
	Check *string `json:"check,omitempty"`
}

// ScheduleSpecApplyConfiguration constructs a declarative configuration of the ScheduleSpec type for use with
// apply.
func ScheduleSpec() *ScheduleSpecApplyConfiguration {
	return &ScheduleSpecApplyConfiguration{}
}

// WithBackup sets the Backup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backup field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithBackup(value string) *ScheduleSpecApplyConfiguration {
	b.Backup = &value
	return b
}

// WithPrune sets the Prune field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prune field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithPrune(value string) *ScheduleSpecApplyConfiguration {
	b.Prune = &value
	return b
}

// WithCheck sets the Check field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Check field is set to the value of the last call.
func (b *ScheduleSpecApplyConfiguration) WithCheck(value string) *ScheduleSpecApplyConfiguration {
	b.Check = &value
	return b
}
