// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/helmetica-framework/ampulla/api/v1"
	apiv1 "github.com/helmetica-framework/ampulla/applyconfiguration/api/v1"
	internal "github.com/helmetica-framework/ampulla/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=backups.helmetica.io, Version=v1
	case v1.SchemeGroupVersion.WithKind("BackupPolicy"):
		return &apiv1.BackupPolicyApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("BackupPolicySpec"):
		return &apiv1.BackupPolicySpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("BackupPolicyStatus"):
		return &apiv1.BackupPolicyStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Retention"):
		return &apiv1.RetentionApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ScheduleSpec"):
		return &apiv1.ScheduleSpecApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
