---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backups.helmetica.io
  resources:
  - backuppolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backups.helmetica.io
  resources:
  - backuppolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
